save_dir: resnet_v1_eembc

model:
  name: resnet_v1_eembc
  filters: 16
  l1: 1e-4
  l2: 0

pruning:
  sparsity: 1.0 

fit:
  compile:
    optimizer: adam
    loss: categorical_crossentropy
  epochs: 100
  patience: 5
  batch_size: 128
  verbose: 1
