name: tiny-mlperf-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyter
    - pydot
    - graphviz
    - git+git://github.com/hls-fpga-machine-learning/hls4ml#egg=hls4ml[profiling]
    - matplotlib
    - numpy
    - PyYAML
    - scikit-learn
    - tensorflow
    - tqdm
    - git+git://github.com/google/qkeras#egg=qkeras
    - setGPU
    - keras-flops
    - git+https://github.com/kentaroy47/keras-Opcounter
