KerasH5:   resnet_v1_eembc/model_best.h5
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7z020clg400-1
ClockPeriod: 5

IOType: io_stream
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 144
    Strategy: Resource
  LayerName:
    conv2d: 
      ReuseFactor: 108
    dense:
      ReuseFactor: 128
    conv2d_5:
      ReuseFactor: 128
    conv2d_8:
      ReuseFactor: 128
