save_dir: resnet_v1_eembc

model:
  name: resnet_v1_eembc_quantized
  filters: 
  - 16
  - 32
  - 64
  l1: 0.001
  l2: 0
  kernels:
  - 3
  - 1
  strides: 
  - 1
  - 2

pruning:
  sparsity: 1.0 

fit:
  compile:
    initial_lr: 0.001
    lr_decay: 0.99
    optimizer: Adam
    loss: categorical_crossentropy
  epochs: 100
  patience: 50
  batch_size: 128
  verbose: 1

quantization:
  logit_total_bits: 7
  logit_int_bits: 0
  activation_total_bits: 7
  activation_int_bits: 3
